# Generated by Django 5.2.17 on 2026-08-23 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_seed_empresa_demo'),
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterUniqueTogether(
            name='sector',
            unique_together={('name', 'company')},
        ),
    ]
