# Generated by Django 5.2.17 on 2026-08-23 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0003_require_sector_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='position',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Cargo inativo não aparece para novos cadastros, mas preserva o histórico.', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='sector',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Setor inativo não aparece para novos cadastros, mas preserva o histórico.', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='sector',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Gestor do setor. Enxerga os colaboradores lotados aqui.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sectors', to=settings.AUTH_USER_MODEL, verbose_name='Gestor responsável'),
        ),
    ]
