# Generated by Django 5.2.17 on 2026-08-24 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, default='', help_text='Rota do app aberta ao tocar na notificação. Ex.: /documents/12', max_length=200, verbose_name='Destino'),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_announcements', models.BooleanField(default=True, verbose_name='Comunicados')),
                ('app_requests', models.BooleanField(default=True, verbose_name='Solicitações')),
                ('app_trainings', models.BooleanField(default=True, verbose_name='Treinamentos')),
                ('app_documents', models.BooleanField(default=True, verbose_name='Documentos')),
                ('app_events', models.BooleanField(default=True, verbose_name='Eventos')),
                ('app_tasks', models.BooleanField(default=True, verbose_name='Tarefas')),
                ('email_announcements', models.BooleanField(default=True, verbose_name='Comunicados')),
                ('email_requests', models.BooleanField(default=True, verbose_name='Solicitações')),
                ('email_trainings', models.BooleanField(default=True, verbose_name='Treinamentos')),
                ('email_documents', models.BooleanField(default=True, verbose_name='Documentos')),
                ('email_events', models.BooleanField(default=False, verbose_name='Eventos')),
                ('email_tasks', models.BooleanField(default=True, verbose_name='Tarefas')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Preferência de notificação',
                'verbose_name_plural': 'Preferências de notificação',
            },
        ),
    ]
