# Generated by Django 5.2.17 on 2026-08-14 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('deadline', models.CharField(choices=[('day1', 'Dia 1'), ('week1', 'Semana 1'), ('month1', 'Mês 1')], db_index=True, max_length=10, verbose_name='Prazo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('sector', models.ForeignKey(blank=True, help_text='Deixe em branco para itens gerais (todos os setores).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='sectors.sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Item do checklist',
                'verbose_name_plural': 'Itens do checklist',
                'ordering': ['deadline', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='checklist.checklistitem', verbose_name='Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_progresses', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Progresso do checklist',
                'verbose_name_plural': 'Progressos do checklist',
                'unique_together': {('user', 'item')},
            },
        ),
    ]
