# Generated by Django 5.2.17 on 2026-08-23 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
        ('companies', '0002_seed_empresa_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='companies.company', verbose_name='Empresa'),
        ),
    ]
