# Generated by Django 5.2.17 on 2026-08-23 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_seed_empresa_demo'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Obrigatório para colaborador/rh_admin. Vazio apenas para o dono do sistema.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('colaborador', 'Colaborador'), ('rh_admin', 'RH Admin'), ('owner', 'Dono do Sistema')], db_index=True, default='colaborador', max_length=20, verbose_name='Papel'),
        ),
    ]
