# Generated by Django 5.2.17 on 2026-08-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_backfill_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, help_text='Usada para calcular prazos reais de integração (checklist/cursos). Vazio para o dono do sistema.', null=True, verbose_name='Data de contratação'),
        ),
    ]
