# Generated by Django 5.2.17 on 2026-08-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_backfill_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sector_leader',
            field=models.BooleanField(default=False, help_text='Colaborador que pode cadastrar treinamentos do próprio setor. Exige setor definido.', verbose_name='Líder do Setor'),
        ),
    ]
