# Generated by Django 5.2.17 on 2026-08-23 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('companies', '0002_seed_empresa_demo'),
        ('sectors', '0004_position_description_position_is_active_and_more'),
        ('users', '0006_user_is_sector_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='URL da foto de perfil. Upload de arquivo fica para uma fase posterior.', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Gestor responsável por este colaborador. Deve ser da mesma empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL, verbose_name='Gestor direto'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Identificação interna do colaborador. Única dentro da empresa.', max_length=30, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('colaborador', 'Colaborador'), ('gestor', 'Gestor'), ('rh_admin', 'RH Admin'), ('company_admin', 'Administrador da Empresa'), ('owner', 'Dono do Sistema')], db_index=True, default='colaborador', max_length=20, verbose_name='Papel'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('registration_number', ''), _negated=True), fields=('company', 'registration_number'), name='unique_registration_per_company'),
        ),
    ]
