# Generated by Django 5.2.17 on 2026-08-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_avatar_url_user_manager_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Usada para o painel de aniversariantes.', null=True, verbose_name='Data de nascimento'),
        ),
    ]
