# Generated by Django 5.2.17 on 2026-08-24 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        ('users', '0008_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Filial onde o colaborador trabalha. Vazio = sem unidade definida.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='units.unit', verbose_name='Unidade'),
        ),
    ]
