# Generated by Django 5.2.17 on 2026-08-24 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_address_company_cnpj_company_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('trigger_event', models.CharField(choices=[('employee.created', 'Colaborador cadastrado'), ('employee.activated', 'Colaborador ativado'), ('employee.deactivated', 'Colaborador desativado'), ('training.assigned', 'Treinamento atribuído'), ('training.completed', 'Treinamento concluído'), ('training.overdue', 'Treinamento atrasado'), ('document.published', 'Documento publicado'), ('document.expiring', 'Documento próximo do vencimento'), ('request.created', 'Solicitação aberta'), ('request.completed', 'Solicitação concluída'), ('announcement.published', 'Comunicado publicado')], db_index=True, max_length=50, verbose_name='Quando acontecer')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Automação',
                'verbose_name_plural': 'Automações',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('sector_id', 'Setor do colaborador'), ('position_id', 'Cargo do colaborador'), ('unit_id', 'Unidade do colaborador'), ('role', 'Papel do colaborador'), ('priority', 'Prioridade'), ('category', 'Categoria')], max_length=40)),
                ('operator', models.CharField(choices=[('eq', 'É igual a'), ('ne', 'É diferente de'), ('in', 'Está entre')], default='eq', max_length=5)),
                ('value', models.CharField(help_text="Para 'está entre', separe por vírgula.", max_length=255)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='automations.automationrule')),
            ],
            options={
                'verbose_name': 'Condição',
                'verbose_name_plural': 'Condições',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_onboarding', 'Gerar tarefas de onboarding'), ('send_notification', 'Enviar notificação no app'), ('send_email', 'Enviar e-mail'), ('assign_training', 'Atribuir treinamento')], max_length=40)),
                ('target', models.CharField(choices=[('employee', 'O colaborador do evento'), ('manager', 'O gestor dele'), ('hr', 'A equipe de RH')], default='employee', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automations.automationrule')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Executada'), ('skipped', 'Ignorada (condição não bateu)'), ('failed', 'Falhou')], db_index=True, max_length=10)),
                ('subject_label', models.CharField(blank=True, default='', help_text='Sobre quem/o quê o disparo aconteceu.', max_length=200)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_runs', to='companies.company')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automations.automationrule')),
            ],
            options={
                'verbose_name': 'Execução de automação',
                'verbose_name_plural': 'Execuções de automação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['company', 'trigger_event', 'is_active'], name='automations_company_dc6ff5_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationrule',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='automation_nome_unico_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['company', '-created_at'], name='automations_company_781111_idx'),
        ),
    ]
