# Generated by Django 5.2.17 on 2026-08-24 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models



def copiar_dados(apps, schema_editor):
    """
    `date` (data pura) vira `start_at` (data e hora), e `author` vira
    `organizer`.

    Eventos antigos não guardavam horário, então assumimos 9h — começo do
    expediente. Sem isto, a coluna nova nasceria vazia e todo evento já
    cadastrado sumiria da agenda.
    """
    from datetime import time

    from django.utils import timezone

    Event = apps.get_model("events", "Event")
    for evento in Event.objects.all():
        if evento.date and evento.start_at is None:
            ingenuo = timezone.datetime.combine(evento.date, time(9, 0))
            evento.start_at = timezone.make_aware(
                ingenuo, timezone.get_current_timezone()
            )
        if evento.author_id and evento.organizer_id is None:
            evento.organizer_id = evento.author_id
        evento.save(update_fields=["start_at", "organizer"])


def reverter_dados(apps, schema_editor):
    """
    Reversível: devolve `start_at` para `date` descartando a hora.

    A hora se perde na volta — é inerente a converter datetime em date, e
    está registrado aqui para não ser surpresa.
    """
    Event = apps.get_model("events", "Event")
    for evento in Event.objects.all():
        if evento.start_at:
            evento.date = evento.start_at.date()
        if evento.organizer_id:
            evento.author_id = evento.organizer_id
        evento.save(update_fields=["date", "author"])


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_cnpj_company_description_and_more'),
        ('events', '0001_initial'),
        ('sectors', '0004_position_description_position_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('going', 'Vou participar'), ('not_going', 'Não vou participar')], max_length=20)),
                ('responded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-responded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_at']},
        ),
        migrations.AddField(
            model_name='event',
            name='allows_rsvp',
            field=models.BooleanField(default=True, help_text='Permite que as pessoas confirmem presença.'),
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Limite de participantes. Vazio = sem limite.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_at',
            field=models.DateTimeField(blank=True, help_text='Opcional. Deve ser depois do início.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Sala, endereço ou link da reunião.', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Organizador'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('cancelled', 'Cancelado')], db_index=True, default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='target_sectors',
            field=models.ManyToManyField(blank=True, related_name='targeted_events', to='sectors.sector'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['company', 'status', 'start_at'], name='events_even_company_afc250_idx'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='eventattendance',
            unique_together={('event', 'user')},
        ),
            # ── Preserva os dados antes de descartar as colunas antigas ────────
        migrations.RunPython(copiar_dados, reverter_dados),
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
