# Generated by Django 5.2.17 on 2026-08-23 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_address_company_cnpj_company_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, help_text='Cópia do nome no momento da ação, para o histórico sobreviver à remoção do usuário.', max_length=150, verbose_name='Nome do autor')),
                ('action', models.CharField(choices=[('login', 'Entrou no sistema'), ('logout', 'Saiu do sistema'), ('create', 'Criou'), ('update', 'Alterou'), ('activate', 'Ativou'), ('deactivate', 'Desativou'), ('role_change', 'Alterou o papel de'), ('delete', 'Excluiu')], db_index=True, max_length=20, verbose_name='Ação')),
                ('resource_type', models.CharField(db_index=True, help_text='Ex.: employee, sector, position, course, company.', max_length=50, verbose_name='Tipo do recurso')),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do recurso')),
                ('resource_label', models.CharField(blank=True, help_text='Nome legível do alvo no momento da ação.', max_length=200, verbose_name='Descrição do recurso')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Apenas nomes de campos alterados. Nunca valores sensíveis.', verbose_name='Detalhes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Quando')),
                ('actor', models.ForeignKey(blank=True, help_text='Nulo se o usuário for removido — o histórico permanece.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('company', models.ForeignKey(blank=True, help_text='Nulo apenas para eventos da plataforma (dono do sistema).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='audit_audit_company_832522_idx')],
            },
        ),
    ]
