# Generated by Django 5.2.17 on 2026-08-14 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('file_url', models.URLField(verbose_name='URL do arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('sector', models.ForeignKey(blank=True, help_text='Deixe em branco para materiais gerais (todos os setores).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='sectors.sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['sector__name', 'title'],
            },
        ),
    ]
