# Generated by Django 5.2.17 on 2026-08-24 00:51

import apps.requests.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_cnpj_company_description_and_more'),
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(blank=True, default='', max_length=10)),
                ('file', models.FileField(upload_to=apps.requests.models.request_attachment_path)),
                ('original_name', models.CharField(blank=True, default='', max_length=150)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='hrrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='requestcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='hrrequest',
            name='due_at',
            field=models.DateTimeField(blank=True, help_text='Prazo de atendimento, derivado da prioridade na abertura.', null=True),
        ),
        migrations.AddField(
            model_name='requestcomment',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Nota interna do RH — o solicitante não vê.'),
        ),
        migrations.AddIndex(
            model_name='hrrequest',
            index=models.Index(fields=['company', 'status', '-created_at'], name='requests_hr_company_a8a863_idx'),
        ),
        migrations.AddIndex(
            model_name='hrrequest',
            index=models.Index(fields=['requester', '-created_at'], name='requests_hr_request_08078f_idx'),
        ),
        migrations.AddIndex(
            model_name='hrrequest',
            index=models.Index(fields=['assigned_to', 'status'], name='requests_hr_assigne_3ece5c_idx'),
        ),
        migrations.AddField(
            model_name='requestattachment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='requests.requestcomment'),
        ),
    ]
