# Generated by Django 5.2.17 on 2026-08-24 00:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_cnpj_company_description_and_more'),
        ('requests', '0002_requestattachment_alter_hrrequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrrequest',
            name='number',
            field=models.CharField(db_index=True, editable=False, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='hrrequest',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_request_number_per_company'),
        ),
    ]
