# Generated by Django 5.2.17 on 2026-08-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_require_course_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deadline',
            field=models.CharField(blank=True, choices=[('day1', 'Dia 1'), ('week1', 'Semana 1'), ('month1', 'Mês 1')], help_text='Opcional. Se definido, some para o cálculo de atraso do colaborador.', max_length=10, null=True, verbose_name='Prazo'),
        ),
    ]
