# Generated by Django 5.2.17 on 2026-08-23 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.ForeignKey(blank=True, help_text='Opcional. O colaborador só pode iniciar este curso após concluir o pré-requisito.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_by', to='courses.course', verbose_name='Pré-requisito'),
        ),
    ]
