# Generated by Django 5.2.17 on 2026-08-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_question_option_quiz_question_quiz_quizattempt_and_more'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='target_units',
            field=models.ManyToManyField(blank=True, help_text='Vazio = todas as unidades da empresa.', related_name='targeted_courses', to='units.unit', verbose_name='Unidades'),
        ),
    ]
