# Generated by Django 5.2.17 on 2026-08-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_target_units'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
