# Generated by Django 5.2.17 on 2026-08-27 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_address_company_cnpj_company_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('mariadb', 'MariaDB'), ('oracle', 'Oracle')], max_length=20, verbose_name='Tipo do banco')),
                ('host', models.CharField(max_length=255)),
                ('porta', models.PositiveIntegerField(blank=True, null=True)),
                ('banco', models.CharField(help_text='No Oracle, informe o service name.', max_length=128, verbose_name='Banco de dados')),
                ('schema', models.CharField(blank=True, default='', help_text='Opcional. Vazio usa o padrão do banco.', max_length=128)),
                ('usuario', models.CharField(max_length=128)),
                ('senha_cifrada', models.TextField(blank=True, default='', editable=False)),
                ('usar_ssl', models.BooleanField(default=False, verbose_name='Usar SSL')),
                ('timeout_segundos', models.PositiveIntegerField(default=10, help_text='Tempo máximo de espera ao conectar.')),
                ('is_active', models.BooleanField(default=True, help_text='Desligada, nenhuma sincronização roda.')),
                ('status', models.CharField(choices=[('untested', 'Nunca testada'), ('ok', 'Conectando'), ('failed', 'Com falha')], default='untested', max_length=10)),
                ('ultimo_teste_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_erro', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_connection', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexão externa',
                'verbose_name_plural': 'Conexões externas',
            },
        ),
    ]
