# Generated by Django 5.2.17 on 2026-08-27 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(choices=[('employee', 'Funcionários'), ('sector', 'Setores'), ('position', 'Cargos')], max_length=20)),
                ('tabela', models.CharField(help_text='Nome da tabela no banco do cliente, como o banco a reporta.', max_length=260)),
                ('campos', models.JSONField(default=dict, help_text='{campo interno: coluna externa}. Campo ausente = não sincronizado.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='integrations.externalconnection')),
            ],
            options={
                'verbose_name': 'Mapeamento',
                'verbose_name_plural': 'Mapeamentos',
                'constraints': [models.UniqueConstraint(fields=('connection', 'entidade'), name='um_mapeamento_por_entidade')],
            },
        ),
    ]
