# Generated by Django 5.2.17 on 2026-08-24 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_cnpj_company_description_and_more'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentacceptance',
            options={'ordering': ['-accepted_at']},
        ),
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': ['name'], 'verbose_name': 'Categoria de documento', 'verbose_name_plural': 'Categorias de documento'},
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Depois desta data o documento deixa de ser exibido como vigente.', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='change_note',
            field=models.CharField(blank=True, default='', help_text='O que mudou nesta versão.', max_length=255),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='checksum',
            field=models.CharField(blank=True, default='', help_text='SHA-256 do conteúdo no momento do upload.', max_length=64),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='extension',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='original_name',
            field=models.CharField(blank=True, default='', help_text='Nome enviado pelo usuário. Só para exibição — nunca usado em caminho.', max_length=150),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='size_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Somente uma versão fica vigente por documento.'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'status', '-created_at'], name='documents_d_company_dc4e1d_idx'),
        ),
    ]
