# Generated by Django 5.2.17 on 2026-08-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentacceptance_options_and_more'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='target_units',
            field=models.ManyToManyField(blank=True, help_text='Vazio = todas as unidades da empresa.', related_name='targeted_%(class)ss', to='units.unit', verbose_name='Unidades'),
        ),
    ]
