# Generated by Django 5.2.17 on 2026-08-24 01:41

import apps.onboarding.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_address_company_cnpj_company_description_and_more'),
        ('sectors', '0004_position_description_position_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, help_text='Prazo. Vazio = tarefa sem data.', null=True)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], db_index=True, default='pending', max_length=15)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Quem executa a tarefa. Vazio = ainda sem responsável.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_onboarding_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tasks', to='companies.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_onboarding_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_onboarding_tasks', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador integrado')),
            ],
            options={
                'verbose_name': 'Tarefa de onboarding',
                'verbose_name_plural': 'Tarefas de onboarding',
                'ordering': ['due_date', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.onboarding.models.onboarding_attachment_path)),
                ('original_name', models.CharField(max_length=255)),
                ('extension', models.CharField(default='', max_length=10)),
                ('mime_type', models.CharField(default='', max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(db_index=True, default='', max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='onboarding.onboardingtask')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo da tarefa',
                'verbose_name_plural': 'Anexos da tarefa',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Visível apenas para RH e gestão.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='onboarding.onboardingtask')),
            ],
            options={
                'verbose_name': 'Comentário da tarefa',
                'verbose_name_plural': 'Comentários da tarefa',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('apply_automatically', models.BooleanField(default=True, help_text='Aplica sozinho ao cadastrar um colaborador que se encaixe.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_templates', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_onboarding_templates', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, help_text='Vazio = vale para qualquer cargo do setor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_templates', to='sectors.position')),
                ('sector', models.ForeignKey(blank=True, help_text='Vazio = vale para qualquer setor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_templates', to='sectors.sector')),
            ],
            options={
                'verbose_name': 'Template de onboarding',
                'verbose_name_plural': 'Templates de onboarding',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('days_offset', models.PositiveIntegerField(default=1, help_text='D+N a partir da admissão. 0 = no próprio dia.')),
                ('responsible', models.CharField(choices=[('employee', 'O próprio colaborador'), ('manager', 'Gestor do setor'), ('hr', 'RH')], default='employee', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='onboarding.onboardingtemplate')),
            ],
            options={
                'verbose_name': 'Tarefa do template',
                'verbose_name_plural': 'Tarefas do template',
                'ordering': ['days_offset', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='template_task',
            field=models.ForeignKey(blank=True, help_text='Origem, quando a tarefa veio de um template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='onboarding.templatetask'),
        ),
        migrations.AddConstraint(
            model_name='onboardingtemplate',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='onboarding_template_nome_unico_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='onboardingtask',
            index=models.Index(fields=['company', 'employee', 'status'], name='onboarding__company_4fce0f_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingtask',
            index=models.Index(fields=['company', 'assigned_to', 'status'], name='onboarding__company_4985e1_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingtask',
            index=models.Index(fields=['company', 'due_date'], name='onboarding__company_3deaf9_idx'),
        ),
    ]
