# Generated by Django 5.2.17 on 2026-08-24 00:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('companies', '0003_company_address_company_cnpj_company_description_and_more'),
        ('sectors', '0004_position_description_position_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Depois desta data o comunicado sai do mural.', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='Marca que as notificações já saíram. Impede envio em duplicidade.', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Quando publicar. Vazio = publicar imediatamente.', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendado'), ('published', 'Publicado'), ('expired', 'Expirado'), ('archived', 'Arquivado')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Urgente ignora a preferência de notificação do usuário.'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['company', 'status', '-published_at'], name='communicati_company_1f7e4b_idx'),
        ),
    ]
